### ISSUE TITLE
Save Manager struggles with loading on startup

### ISSUE THREAD

**Issue by SalbugVR** [ChrisFeline/ToNSaveManager#18]
When the save manager has a lot of logs and save codes stored, it struggles to load for a while on startup.

**Comment by ChrisFeline** [comment]
Hey, thanks for reporting. This happens because VRChat logs persist for some users, like me. Probably because VRChat fails to delete them or some launch parameters might make them persist that way. And I am reading logs to recover saves just in case.

Since It is always reading logs on app start up, it takes some time to parse every line for each log file.

I will make reading already parsed logs an optional feature, that should make things load quickly.

**Comment by SalbugVR** [comment]
Yup. After updating with the artifact it loads swiftly for me now and no longer hangs on startup.
