### ISSUE TITLE
Add RGB OSC parameter

### ISSUE THREAD

**Issue by nomlasvrc** [ChrisFeline/ToNSaveManager#62]
Please add RGB OSC parameter representing the HUD Terror Color.
This will make it easier to modify avatars.

**Comment by ChrisFeline** [comment]
Is it because I implemented it in HSV? https://github.com/ChrisFeline/ToNSaveManager/blob/main/Docs/OSC/OSC_Parameters.md#colors

As far as I know, you can't animate the R, G and B color channels individually on a single color property in a Shader. Unless there's a Shader where you can set the RGB directly?
As a bonus, I am working on a unity script/prefab that will allow you to animate any property on any Shader that you might use.

Methods to convert HSV to RGB in Shaders is very straight forward.
https://gist.github.com/iUltimateLP/5129149bf82757b31542

You can reply with any idea or clarifications and I'll consider it.

**Comment by nomlasvrc** [comment]
> Is it because I implemented it in HSV?

Yes, it is.
For example, the lilToon (https://booth.pm/ja/items/3087170) shader can specify RGB directly, but not HSV. You can edit the shader or implement it in BrendTree, but since this shader is used by most avatars in Japan, many people would benefit from RGB OSC parameters.

**Comment by ChrisFeline** [comment]
I understand (I'm a lilToon user too) I didn't know it had a per channel RGB coloring feature.
So, would it be good enough if I add an option in the settings to send RGB instead, HSV being the default?

**Comment by ChrisFeline** [comment]
Alright, next update there will be an extra setting on the menu.
Then the parameters will be sent as:
`ToN_ColorR`
`ToN_ColorG`
`ToN_ColorB`

**Comment by nomlasvrc** [comment]
Thank you!

**Comment by ChrisFeline** [comment]
https://github.com/user-attachments/assets/37c749b1-cffd-4b03-b6bd-cc265ec67852

Is this good? When you click this button, it will change between the HSV and RGB modes.
If you wanna translate the new keys beforehand, you can find the new strings on this commit: https://github.com/ChrisFeline/ToNSaveManager/commit/5fea843ad3ee51add73543b0c65f5328ce34a08a

**Comment by nomlasvrc** [comment]
Good! I added a new key in #65.
